Update CowboyDelDia.jsx
The-Cowboys/the-cowboy-day pull request #35
Opened 2024-03-14 19:20 UTC by JLeonN

Anteriormente, el componente CowboyDelDia.js utilizaba el endpoint /api/putos/today.

Ahora, se ha actualizado para usar /api/cowboys/today.

Además, se han modificado las funciones y variables que contenían la palabra "puto" por "cowboy".

2024-03-14 19:43 UTC, MallicTesla approved these changes

2024-03-15 08:43 UTC, francosang requested changes

2024-03-15 08:43 UTC, francosang commented on frontend/src/Pagina/CowboyDelDia.jsx
> +  const [cowboys, setCowboys] = useState(null);
Cada dia hay un solo cowboy.
Este estado es para solo un cowboy.

Significa que el nombre debe estar en singular, sin la s del final, solo `cowboy`.

Lo ideal searia cambiar todos los `cowboys` por `cowboy` 😉

2024-03-15 08:43 UTC, francosang commented on frontend/src/Pagina/CowboyDelDia.jsx
>      }
Viste que aca hay un ejemplo de try y catych? No me acordaba.

2024-03-15 08:43 UTC, francosang commented on frontend/src/Pagina/CowboyDelDia.jsx
>            )
Tampoco me acordaba de esto, pero aca tambien hay un ejemplo para mostrar componentes segun una condicion.

El boton solo aparece si el usuario NO hizo click.
Cuando el usuario hace click, cambia el boton por el mensaje.

Algo asi:
```
boton no apretado {
   mostrar boton
} si no {
   mostrar mensaje
}
```

Este es el codigo real:
```jsx
     {
          !clicked ? (
            <button className='btn btn-dark' onClick={click}>
              ¿Quien es el Cowboy del día?
            </button>
          ) : (
            <div>
              <p>El cowboy de hoy es....</p>
              <h2>{cowboys}</h2>
            </div>
          )
     }
```

2024-03-15 09:54 UTC, JLeonN commented on frontend/src/Pagina/CowboyDelDia.jsx
>            )
Sí, es verdad, Franco
Ya lo estoy mirando para usarlo en un futuro porque me gustó la idea.

2024-03-15 09:55 UTC, JLeonN commented on frontend/src/Pagina/CowboyDelDia.jsx
> +  const [cowboys, setCowboys] = useState(null);
voy

2024-03-16 17:40 UTC, francosang approved these changes

2024-03-16 17:41 UTC, francosang commented on frontend/src/Pagina/CowboyDelDia.jsx
> +  const [cowboys, setCowboys] = useState(null);
La funcion `fetchCowboys` sigue estando en plural, debería ser `fetchCowboy`. Pero tranqui, es lo mismo.

2024-03-16 17:42 UTC, francosang commented
Dale al boton verde!

2024-03-16 18:44 UTC, merged