Componente cowboy del día
The-Cowboys/the-cowboy-day pull request #59
Opened 2024-04-04 10:41 UTC by JLeonN

Se ha implementado el componente <CowboyDelDia /> con su estructura básica.
Se ha establecido el diseño inicial del componente, incluyendo una tarjeta y una lista de participantes.
Se han realizado ajustes en la presentación visual del componente para indicar que la funcionalidad está en desarrollo.
Se han creado planes para futuras mejoras en el contenido y la estructura del componente, especialmente para mostrar más información sobre el "cowboy del día".
Se están llevando a cabo esfuerzos para alinear el comportamiento del componente con otros componentes existentes, como <ElMasTonto />.

2024-04-04 10:51 UTC, francosang commented on frontend/src/Hooks/useCowboyDelDia.js
>      const cowboyName = await fetchCowboysToday();
No es necesario hacerlo ahora, pero aca habria que poner un try-catch para atrapar posibles errores.
Esto esta relacionado con las nuevas tarjetas que te puse en trello.

2024-04-04 10:51 UTC, francosang commented on frontend/src/API/Api.js
> +  const resp = await api.get(
Me parece bien haber borrado ese try-catch de aca.

2024-04-04 10:51 UTC, francosang commented on frontend/src/Pagina/CowboyDelDia/ComponetesDelCowboyDelDia/LisPartiCowboyDelDia.jsx
> +const ListaParticipantes = () => {
Vamos a cambiarle el nombre.
Que te parecen estos ejemplos?
 - `ListaCowboysDelDia`
 - `ListaCowboys`

2024-04-04 10:51 UTC, francosang commented on frontend/src/Pagina/ElMasTonto/ElMasTonto.jsx
>          <ListaParticipantes />
Habria que cambiar el nombre de este componente. 
Ya que muestra la lista de tontos, que te parece ponerle `ListaTontos`?
Asi queda la `ListaCowboys` y `ListaTontos`?

2024-04-04 10:54 UTC, JLeonN commented on frontend/src/Pagina/CowboyDelDia/ComponetesDelCowboyDelDia/LisPartiCowboyDelDia.jsx
> +const ListaParticipantes = () => {
Si esta bien de bien 
Me gusta =  ListaCowboysDelDia

2024-04-04 15:45 UTC, francosang approved these changes

2024-04-04 17:59 UTC, francosang requested changes

2024-04-04 17:59 UTC, francosang commented on frontend/src/Hooks/useCowboyDelDia.js
>      clicked,
Me acabo de dar cuenta que si borraste el `click`, también hay que borrar el `clicked` junto con su estado.

Es decir, hay que borrar TODO lo relacionado con los clicks, porque ya no se usa nada.

2024-04-05 11:23 UTC, franco-stuart approved these changes
Sote! Aprobaooo 12! Sobresaliente, siga asi!

2024-04-05 11:23 UTC, franco-stuart approved these changes

2024-04-05 11:24 UTC, francosang approved these changes

2024-04-05 11:24 UTC, merged