Inicio de sesión - HTML y CSS
The-Cowboys/the-cowboy-day pull request #64
Opened 2024-04-07 20:08 UTC by JLeonN

2024-04-12 08:13 UTC, franco-stuart approved these changes

2024-04-12 08:13 UTC, franco-stuart commented on frontend/src/Pagina/InicioDeSesión/Login.jsx
> +    window.location.href = "/EstructuraDePerfil/1";
La navegacion se hace con el hook, creo que se llamaba `useNavigate()` o algo asi.
Similar a como hiciste en otras paginas.

2024-04-12 08:13 UTC, franco-stuart commented on frontend/src/Pagina/InicioDeSesión/Login.jsx
> +    window.location.href = "/EstructuraDePerfil/1";
@JLeonN la navegación se hace así: https://github.com/The-Cowboys/the-cowboy-day/blob/8fc2138b54cf90a170c1c6fbc7bd642623e04bf0/frontend/src/Hooks/useObtenerParticipante.js#L9

Antes que nada, acordate SIEMPRE de buscar ejemplos en el codigo.
Es decir, siempre que tengas que hacer algo, busca cosas similares en el codigo.
Pensá que otras cosas iguales o parecidas pueden existir.

Por ejemplo, ya habias hecho ejemplos de navegacion cuando vas del participante a la lista del titulo, o cuando hay un error.

2024-04-16 17:00 UTC, francosang commented on frontend/src/API/Api.js
> +export async function InicioSesion(sesion) {
Has programado 285647425 funciones, todas esmpiezan con minuscula y deben ser verbos o acciones.

Cambiar a `inicarSesion`.

2024-04-16 17:01 UTC, francosang commented on frontend/src/Pagina/InicioDeSesión/Login.jsx
> +  const IniciarSesion = async () => {
Igual que mi comentario antrerior, debe empezar en minuscula y que la primera palabra sea un verbo.

2024-04-16 17:02 UTC, francosang commented on frontend/src/Pagina/InicioDeSesión/Login.jsx
> +    // 2 guardar el token en la sesion ? buscar
Borrar estos comentarios.

2024-04-16 17:05 UTC, francosang approved these changes

2024-04-16 17:05 UTC, francosang commented on frontend/src/Pagina/InicioDeSesión/Registro.jsx
> +            // onChange={(e) => setEmail(e.target.value)}
Esto esta sin terminar.

2024-04-16 17:05 UTC, francosang commented on frontend/src/Pagina/InicioDeSesión/Registro.jsx
> +            // onChange={(e) => setContraseña(e.target.value)}
Esto esta sin terminar.

2024-04-16 17:05 UTC, francosang commented on frontend/src/Pagina/InicioDeSesión/Registro.jsx
> +              // onClick={IniciarSesion}
Esta sin terminar.

2024-04-16 17:05 UTC, francosang commented on frontend/src/Pagina/InicioDeSesión/Registro.jsx
> +const Registro = () => {
Si te sirve de ayuda, acordate de estas preguntas:

```js
// Que muestra mi pantalla?
//  - 
//
// Variables del estado:
//  - 
//
// Acciones de la pantalla:
//  - 
//
//  Pasos:
//  1. declarar los estados
//  2. asociar los estado al HTML
//  3. hacer una funcion para cada accion
```

2024-04-16 17:06 UTC, francosang requested changes
Daleeeee, maní quemado!

2024-04-16 21:54 UTC, francosang approved these changes

2024-04-16 21:56 UTC, merged